name: pull-request
on:
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go 1.20
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.x'
      - name: Install Pulumi CLI
        uses: pulumi/actions@v4
        with:
          pulumi-version: "v3.74.0"
      - name: Install kubernetes plugin
        run: pulumi plugin install resource kubernetes
      - name: Run tests
        run: go test ./...
